version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres-ms
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: ms-user
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
